version: "3.3"
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "todoapp"
            MYSQL_USER: "user"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
